"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "te" | "en";

const messages = {
  te: {
    back: "వెనక్కి",
    appName: "ట్రాక్టర్ లెక్కలు",
    appSubtitle: "ట్రాక్టర్ పని వివరాలు",
    language: "English",
    languageLabel: "భాషను English కు మార్చండి",
    signOut: "లాగ్ అవుట్",
    loading: "లోడ్ అవుతోంది...",
    checkingSession: "లాగిన్ వివరాలు చూస్తున్నాం...",
    home: "హోమ్",
    addWork: "పని జోడించండి",
    customers: "రైతులు",
    records: "పని వివరాలు",
    payments: "చెల్లింపులు",
    workTypes: "పని రకాలు",
    settings: "సెట్టింగులు",
    overview: "మొత్తం లెక్క",
    todayRecords: "పని వివరాలు",
    overviewHelp: "పని, వచ్చిన డబ్బు, రావాల్సిన బాకీ అన్నీ ఒకే చోట.",
    totalWork: "మొత్తం పని విలువ",
    received: "వచ్చిన డబ్బు",
    pending: "రావాల్సిన బాకీ",
    recentWork: "ఇటీవలి పనులు",
    recordCount: "{count} పనులు",
    noWork: "ఇంకా పని నమోదు చేయలేదు",
    noWorkHelp: "మొదటి పనిని నమోదు చేయడానికి పని జోడించండి నొక్కండి.",
    farmer: "రైతు",
    paid: "చెల్లించారు",
    partiallyPaid: "కొంత చెల్లించారు",
    paymentDue: "చెల్లించాలి",
    dueShort: "{amount} రావాలి",
    editWork: "సవరించు",
    shareReceipt: "పంచుకోండి",
    shareDetails: "వివరాలు పంపండి",
    shareAllDetails: "అన్ని వివరాలు పంపండి",
    customerList: "రైతుల జాబితా",
    customerHelp: "రైతును వెతికి పూర్తి లెక్క చూడండి.",
    search: "వెతకండి",
    searchPlaceholder: "పేరు లేదా ఫోన్ నంబర్ వెతకండి",
    noPhone: "ఫోన్ నంబర్ లేదు",
    balanceDue: "రావాల్సిన బాకీ",
    customerBalance: "బాకీ",
    noBalance: "బాకీ లేదు",
    noFarmers: "రైతులు కనిపించలేదు",
    noFarmersHelp: "వేరే పేరు లేదా ఫోన్ నంబర్‌తో వెతకండి.",
    allFarmers: "రైతులందరూ",
    totalAmount: "మొత్తం డబ్బు",
    workPaymentHistory: "పని, చెల్లింపుల వివరాలు",
    noFarmerWork: "ఈ రైతుకు పని లేదు",
    noFarmerWorkHelp: "నమోదు చేసిన పనులు ఇక్కడ కనిపిస్తాయి.",
    viewOldWorkHistory: "పాత పనులు / బాకీలు చూడండి",
    noOldWorkHistory: "పాత పనుల వివరాలు లేవు",
    addPayment: "డబ్బు అందింది",
    payment: "చెల్లింపు",
    workTypesHelp: "మీరు తరచుగా చేసే ట్రాక్టర్ పనులను నమోదు చేయండి.",
    newWorkType: "కొత్త పని రకం",
    workTypeExample: "ఉదా: దుక్కి",
    add: "జోడించండి",
    availableInForm: "అందుబాటులో ఉంది",
    hiddenFromForm: "నిలిపివేశారు",
    acreRate: "ఎకరానికి ధర",
    hourRate: "గంటకు ధర",
    saveRates: "ధరలు సేవ్ చేయండి",
    ratesSaved: "ధరలు సేవ్ అయ్యాయి",
    newRecord: "కొత్త పని",
    editRecord: "పని మార్చండి",
    existingFarmer: "పాత రైతు",
    newFarmer: "కొత్త రైతు",
    farmerName: "రైతు పేరు",
    selectFarmer: "రైతును ఎంచుకోండి",
    phoneNumber: "ఫోన్ నంబర్",
    optional: "అవసరం లేకపోతే ఖాళీగా ఉంచండి",
    selectContact: "కాంటాక్ట్ ఎంచుకోండి",
    chooseContactNumber: "ఫోన్ నంబర్ ఎంచుకోండి",
    contactPickerError: "కాంటాక్ట్‌ను తెరవలేకపోయాము. వివరాలను చేతితో నమోదు చేయండి.",
    workDate: "పని తేదీ",
    workType: "పని రకం",
    selectWorkType: "పని రకాన్ని ఎంచుకోండి",
    chargeBasis: "లెక్కింపు విధానం",
    perHour: "గంటకు",
    perAcre: "ఎకరానికి",
    hoursWorked: "పని చేసిన గంటలు",
    acres: "ఎకరాలు",
    ratePerHour: "గంటకు ధర",
    ratePerAcre: "ఎకరానికి ధర",
    amountReceived: "తీసుకున్న డబ్బు",
    balanceAfterPayments: "చెల్లింపుల తర్వాత రావాల్సిన డబ్బు",
    save: "సేవ్ చేయండి",
    saveChanges: "మార్పులు సేవ్ చేయండి",
    cancel: "రద్దు",
    saving: "సేవ్ అవుతోంది...",
    paymentDate: "చెల్లింపు తేదీ",
    amount: "డబ్బు",
    paymentMethod: "చెల్లింపు విధానం",
    selectPaymentMethod: "చెల్లింపు విధానాన్ని ఎంచుకోండి",
    cash: "నగదు",
    upi: "UPI",
    bankTransfer: "బ్యాంక్ బదిలీ",
    other: "ఇతర",
    savePayment: "చెల్లింపు సేవ్ చేయండి",
    savedSuccessfully: "వివరాలు సేవ్ అయ్యాయి",
    workUpdated: "పని వివరాలు మార్చబడ్డాయి",
    paymentSaved: "చెల్లింపు సేవ్ అయ్యింది",
    workTypeAdded: "పని రకం జోడించబడింది",
    shareReceiptTitle: "రసీదు పంపండి",
    customerStatementTitle: "రైతు పూర్తి ఖాతా వివరాలు",
    sharedWorkDetails: "పని వివరాలు",
    sharedQuantity: "పరిమాణం",
    remainingBalance: "మిగిలిన బాకీ",
    totalPendingBalance: "చెల్లించాల్సిన బాకీ",
    noPendingBalance: "బాకీ లేదు",
    sendWhatsApp: "వాట్సాప్‌లో పంపండి",
    sendSms: "SMS ద్వారా పంపండి",
    done: "పూర్తయింది",
    receiptTitle: "ట్రాక్టర్ పని రసీదు",
    receiptFarmer: "రైతు",
    receiptDate: "తేదీ",
    receiptWork: "పని",
    receiptRate: "ధర",
    receiptTotal: "మొత్తం డబ్బు",
    receiptReceived: "తీసుకున్న డబ్బు",
    receiptBalance: "రావాల్సిన డబ్బు",
    thankYou: "ధన్యవాదాలు",
    loginTitle: "ట్రాక్టర్ లెక్కలు",
    loginIllustrationAlt: "పచ్చని పొలంలో ట్రాక్టర్‌తో రైతు",
    email: "ఈమెయిల్",
    password: "పాస్‌వర్డ్",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    forgotPasswordTitle: "పాస్‌వర్డ్ రీసెట్ లింక్ పొందండి",
    forgotPasswordHelp: "మీ ఖాతాకు నమోదు చేసిన ఇమెయిల్‌ను నమోదు చేయండి.",
    sendResetLink: "రీసెట్ లింక్ పంపండి",
    sendingResetLink: "లింక్ పంపుతున్నాం...",
    resetEmailConfirmation: "ఈ ఇమెయిల్‌తో ఖాతా ఉంటే, పాస్‌వర్డ్ రీసెట్ లింక్ పంపబడుతుంది.",
    backToLogin: "లాగిన్‌కు తిరిగి వెళ్లండి",
    changePassword: "పాస్‌వర్డ్ మార్చండి",
    changePasswordHelp: "మీ Supabase ఖాతాకు కొత్త పాస్‌వర్డ్‌ను అమర్చండి.",
    currentPassword: "ప్రస్తుత పాస్‌వర్డ్",
    newPassword: "కొత్త పాస్‌వర్డ్",
    confirmPassword: "కొత్త పాస్‌వర్డ్‌ను మళ్లీ నమోదు చేయండి",
    passwordRequirements: "Supabaseలో అమర్చిన పొడవు మరియు భద్రతా నియమాలకు సరిపోయే పాస్‌వర్డ్ ఉపయోగించండి.",
    passwordsDoNotMatch: "రెండు పాస్‌వర్డ్‌లు ఒకేలా లేవు.",
    passwordRequired: "కొత్త పాస్‌వర్డ్‌ను నమోదు చేయండి.",
    currentPasswordRequired: "కొనసాగడానికి ప్రస్తుత పాస్‌వర్డ్‌ను నమోదు చేయండి.",
    updatePassword: "పాస్‌వర్డ్ నవీకరించండి",
    updatingPassword: "పాస్‌వర్డ్ నవీకరిస్తున్నాం...",
    passwordChanged: "పాస్‌వర్డ్ విజయవంతంగా మార్చబడింది.",
    passwordUpdateFailed: "పాస్‌వర్డ్ మార్చలేకపోయాం. మళ్లీ ప్రయత్నించండి.",
    passwordTooShort: "పాస్‌వర్డ్ కనీసం {count} అక్షరాలు ఉండాలి.",
    passwordLengthRule: "పాస్‌వర్డ్ ఇంకా పొడవుగా ఉండాలి.",
    passwordCharacterRule: "పాస్‌వర్డ్‌లో అవసరమైన అక్షరాలు, అంకెలు లేదా ప్రత్యేక గుర్తులు ఉండాలి.",
    passwordLeakedRule: "ఈ పాస్‌వర్డ్ సురక్షితం కాదు. వేరే పాస్‌వర్డ్ ఉపయోగించండి.",
    passwordWeak: "పాస్‌వర్డ్ భద్రతా నియమాలకు సరిపోలలేదు.",
    passwordSame: "కొత్త పాస్‌వర్డ్ ప్రస్తుత పాస్‌వర్డ్‌కు భిన్నంగా ఉండాలి.",
    reauthCode: "ఇమెయిల్‌లో వచ్చిన 6 అంకెల కోడ్",
    reauthCodeHelp: "భద్రత కోసం మీ ఇమెయిల్‌కు పంపిన కోడ్‌ను నమోదు చేయండి.",
    reauthCodeSent: "మీ ఇమెయిల్‌కు ధృవీకరణ కోడ్ పంపబడింది.",
    reauthCodeInvalid: "ధృవీకరణ కోడ్ తప్పుగా ఉంది లేదా గడువు ముగిసింది.",
    reauthCurrentRequired: "భద్రత కోసం మీ ప్రస్తుత పాస్‌వర్డ్‌ను ధృవీకరించండి.",
    resetPasswordTitle: "కొత్త పాస్‌వర్డ్ అమర్చండి",
    resetPasswordHelp: "మీ ఖాతా కోసం కొత్త పాస్‌వర్డ్‌ను నమోదు చేయండి.",
    recoveryLinkInvalid: "ఈ పాస్‌వర్డ్ రీసెట్ లింక్ చెల్లదు. మరో లింక్ కోరండి.",
    recoveryLinkExpiredOrUsed: "ఈ పాస్‌వర్డ్ రీసెట్ లింక్ గడువు ముగిసింది లేదా ఇప్పటికే ఉపయోగించబడింది. మరో లింక్ కోరండి.",
    requestAnotherLink: "మరో రీసెట్ లింక్ కోరండి",
    continueToApp: "యాప్‌లోకి వెళ్లండి",
    showPassword: "పాస్‌వర్డ్ చూపించండి",
    hidePassword: "పాస్‌వర్డ్ దాచండి",
    yourName: "మీ పేరు",
    enterYourName: "మీ పూర్తి పేరు",
    enterPhoneNumber: "10 అంకెల మొబైల్ నంబర్",
    signIn: "లాగిన్ చేయండి",
    signUp: "ఖాతా తెరవండి",
    registerBtn: "ఖాతా తెరవండి",
    signingUp: "ఖాతా సృష్టించబడుతోంది...",
    createAccount: "కొత్త ఖాతా తెరవండి",
    registerHelp: "మీ ట్రాక్టర్ లెక్కల కోసం మీ వివరాలతో కొత్త ఖాతాను సృష్టించండి.",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి",
    dontHaveAccount: "కొత్త ఖాతా కావాలా? ఇక్కడ నమోదు చేసుకోండి",
    registerSuccessCheckEmail: "రిజిస్ట్రేషన్ పూర్తయింది! దయచేసి లాగిన్ చేయండి.",
    loginWelcome: "తిరిగి స్వాగతం",
    loginHelp: "మీ ట్రాక్టర్ లెక్కలను కొనసాగించడానికి లాగిన్ చేయండి.",
    loginSecurityNote: "మీ ఖాతా సురక్షితంగా ఉంది",
    signingIn: "లాగిన్ అవుతోంది...",
    privateRecords: "మీ లెక్కలు మీకు మాత్రమే కనిపిస్తాయి.",
    setupTitle: "Supabase ను కనెక్ట్ చేయండి",
    setupOnce: "ఒక్కసారి సెటప్",
    setupHelp: "ఈ రెండు Supabase వివరాలను .env.local లో జోడించి యాప్‌ను మళ్లీ ప్రారంభించండి.",
    setupDocs: "పూర్తి వివరాలు README.md లో ఉన్నాయి.",
    close: "మూసివేయండి",
    noWorkTypes: "పని రకాలు లేవు. పని రకాల పేజీలో జోడించండి.",
    invalidAmounts: "సున్నా కంటే ఎక్కువ పరిమాణం, సున్నా లేదా అంతకంటే ఎక్కువ ధర నమోదు చేయండి.",
    totalBelowPaid: "ఇప్పటికే తీసుకున్న {amount} కంటే మొత్తం డబ్బు తక్కువగా ఉండకూడదు.",
    receivedTooHigh: "తీసుకున్న డబ్బు మొత్తం డబ్బు కంటే ఎక్కువగా ఉండకూడదు.",
    chooseWorkType: "పని రకాన్ని ఎంచుకోండి.",
    enterFarmerName: "రైతు పేరు నమోదు చేయండి.",
    chooseFarmer: "రైతును ఎంచుకోండి.",
    choosePaymentMethod: "చెల్లింపు విధానాన్ని ఎంచుకోండి.",
    paymentPositive: "సున్నా కంటే ఎక్కువ చెల్లింపు నమోదు చేయండి.",
    paymentTooHigh: "చెల్లింపు రావాల్సిన {amount} కంటే ఎక్కువగా ఉండకూడదు.",
    customerOutstandingBalance: "మొత్తం రావాల్సిన బాకీ",
    remainingAfterPayment: "ఈ చెల్లింపు తర్వాత మిగిలిన బాకీ",
    oldestWorkAllocationHelp: "ఈ డబ్బు పాత బాకీ ఉన్న పనులకు ముందుగా జమ అవుతుంది.",
    customerPaymentSaved: "రైతు చెల్లింపు సేవ్ అయ్యింది.",
    customerBalanceChanged: "బాకీ మొత్తం మారింది. వివరాలను రిఫ్రెష్ చేసి మళ్లీ ప్రయత్నించండి.",
    paymentRequestConflict: "ఈ చెల్లింపు అభ్యర్థన వివరాలు మారాయి. ఫారమ్‌ను మూసి మళ్లీ తెరవండి.",
    workSavedPaymentFailed: "పని సేవ్ అయ్యింది, కానీ చెల్లింపు సేవ్ కాలేదు: {error}",
    technicalError: "పని పూర్తి కాలేదు. మళ్లీ ప్రయత్నించండి. వివరాలు: {error}",
    sessionExpired: "మీ లాగిన్ సమయం ముగిసింది. మళ్లీ లాగిన్ చేయండి.",
    invalidLogin: "ఈమెయిల్ లేదా పాస్‌వర్డ్ సరైనది కాదు.",
    networkError: "ఇంటర్నెట్ కనెక్షన్‌ను చూసి మళ్లీ ప్రయత్నించండి.",
    appTagline: "మీ ట్రాక్టర్ పనుల లెక్కలు ఇక మొబైల్ లోనే",
    greeting: "నమస్కారం",
    pendingDuesSection: "బాకీ ఉన్నవారు",
    viewAll: "అందర్నీ చూడండి",
    addNewWorkHome: "+ కొత్త పని నమోదు చేయండి",
    addNewCustomer: "+ కొత్త కస్టమర్",
    customerDetails: "కస్టమర్ వివరాలు",
    whoseWork: "ఎవరి పని?",
    whatWorkDone: "ఏ పని చేశారు?",
    howManyAcres: "ఎన్ని ఎకరాలు?",
    howManyHours: "ఎన్ని గంటలు?",
    ratePerAcreShort: "ఎకరానికి రేటు",
    ratePerHourShort: "గంటకు రేటు",
    nowReceived: "ఇప్పుడు ఇచ్చిన డబ్బు",
    saveWorkBtn: "పని సేవ్ చేయండి",
    recordPaymentBtn: "డబ్బు నమోదు చేయండి",
    currentBalance: "ప్రస్తుత బాకీ",
    howMuchPaid: "ఎంత ఇచ్చారు?",
    remainingBalanceDue: "మిగిలిన బాకీ",
    workSavedTitle: "పని సేవ్ అయ్యింది!",
    shareOnWhatsApp: "WhatsApp లో పంపండి",
    goToHome: "హోమ్‌ కి వెళ్లండి",
    oldRecords: "పాత లెక్కలు",
    allWorks: "అన్నీ",
    workTypesAndRates: "పని రకాలు & రేట్లు",
    addWorkType: "కొత్త పని రకం",
    editWorkType: "పని రకం మార్చండి",
    editCustomer: "రైతు వివరాలు మార్చండి",
    configuredRateMissing: "రేటు సెట్ చేయండి",
    customerUpdated: "రైతు వివరాలు నవీకరించబడ్డాయి",
    payableBalanceLabel: "చెల్లించాల్సిన బాకీ",
    workTypeName: "పని రకం పేరు",
    workTypeImage: "పని చిత్రం",
    workTypeImageHelp: "ఐచ్ఛికం · JPEG, PNG, WebP · గరిష్ఠంగా 2 MB. వ్యక్తిగత వివరాలు లేని పని చిత్రాలను మాత్రమే ఎంచుకోండి.",
    changeWorkTypeImage: "చిత్రం మార్చండి",
    removeWorkTypeImage: "చిత్రం తీసివేయండి",
    imageInvalidType: "JPEG, PNG లేదా WebP చిత్రాన్ని ఎంచుకోండి.",
    imageTooLarge: "చిత్రం 2 MB కంటే ఎక్కువగా ఉండకూడదు.",
    workTypeUnavailable: "పని రకం అందుబాటులో లేదు. పని రకాల పేజీకి తిరిగి వెళ్లండి.",
    enterWorkTypeName: "పని రకం పేరు నమోదు చేయండి.",
    invalidRate: "రేటు సున్నా లేదా అంతకంటే ఎక్కువగా ఉండాలి.",
    workTypeUpdated: "పని రకం నవీకరించబడింది",
    rateNotConfigured: "రేటు సెట్ చేయండి లేదా నమోదు చేయండి.",
    unsavedChangesPrompt: "సేవ్ చేయని మార్పులు ఉన్నాయి. ఏం చేయాలి?",
    continueEditing: "మార్చుతూనే ఉండండి",
    discardChanges: "మార్పులు వదిలేయండి",
    changePasswordOption: "పాస్‌వర్డ్ మార్చుకోండి",
    call: "కాల్ చేయండి",
    navHome: "హోమ్",
    navCustomers: "కస్టమర్లు",
    navWork: "పని",
    navPending: "బాకీలు",
    navSettings: "సెట్టింగ్స్",
    fullyPaid: "పూర్తిగా చెల్లించారు",
    pendingDueBadge: "బాకీ",
    loginBtn: "లాగిన్",
    noPendingDues: "ప్రస్తుతం ఎవరికీ బాకీ లేదు",
  },
  en: {
    back: "Back",
    appName: "Tractor Records",
    appSubtitle: "Tractor work records",
    language: "తెలుగు",
    languageLabel: "Switch language to Telugu",
    signOut: "Sign out",
    loading: "Loading...",
    checkingSession: "Checking your login...",
    home: "Home",
    addWork: "Add Work",
    customers: "Customers",
    records: "Records",
    payments: "Payments",
    workTypes: "Work types",
    settings: "Settings",
    overview: "Overview",
    todayRecords: "Work records",
    overviewHelp: "Work, payments and pending amounts in one place.",
    totalWork: "Total work",
    received: "Amount received",
    pending: "Balance due",
    recentWork: "Recent work",
    recordCount: "{count} records",
    noWork: "No work saved yet",
    noWorkHelp: "Tap Add Work to save the first tractor job.",
    farmer: "Farmer",
    paid: "Paid",
    partiallyPaid: "Partially paid",
    paymentDue: "Payment due",
    dueShort: "{amount} due",
    editWork: "Edit work",
    shareReceipt: "Share",
    shareDetails: "Share details",
    shareAllDetails: "Share all details",
    customerList: "Customer list",
    customerHelp: "Search and open a farmer's full account.",
    search: "Search",
    searchPlaceholder: "Search name or phone number",
    noPhone: "No phone number",
    balanceDue: "Balance due",
    customerBalance: "Balance",
    noBalance: "No balance due",
    noFarmers: "No farmers found",
    noFarmersHelp: "Try a different name or phone number.",
    allFarmers: "All farmers",
    totalAmount: "Total amount",
    workPaymentHistory: "Work and payment history",
    noFarmerWork: "No work for this farmer",
    noFarmerWorkHelp: "Their saved work will appear here.",
    viewOldWorkHistory: "View previous work / balances",
    noOldWorkHistory: "No previous work details",
    addPayment: "Add payment",
    payment: "Payment",
    workTypesHelp: "Add the tractor jobs you commonly do.",
    newWorkType: "New work type",
    workTypeExample: "Example: Ploughing",
    add: "Add",
    availableInForm: "Available in form",
    hiddenFromForm: "Hidden from form",
    acreRate: "Rate per acre",
    hourRate: "Rate per hour",
    saveRates: "Save rates",
    ratesSaved: "Rates saved",
    newRecord: "New record",
    editRecord: "Edit record",
    existingFarmer: "Existing farmer",
    newFarmer: "New farmer",
    farmerName: "Farmer name",
    selectFarmer: "Select farmer",
    phoneNumber: "Phone number",
    optional: "Leave empty if unavailable",
    selectContact: "Select contact",
    chooseContactNumber: "Choose a phone number",
    contactPickerError: "Could not open contacts. Enter the details manually.",
    workDate: "Work date",
    workType: "Work type",
    selectWorkType: "Select work type",
    chargeBasis: "Charge basis",
    perHour: "Per hour",
    perAcre: "Per acre",
    hoursWorked: "Hours worked",
    acres: "Acres",
    ratePerHour: "Rate per hour",
    ratePerAcre: "Rate per acre",
    amountReceived: "Amount received",
    balanceAfterPayments: "Balance after saved payments",
    save: "Save",
    saveChanges: "Save changes",
    cancel: "Cancel",
    saving: "Saving...",
    paymentDate: "Payment date",
    amount: "Amount",
    paymentMethod: "Payment method",
    selectPaymentMethod: "Select payment method",
    cash: "Cash",
    upi: "UPI",
    bankTransfer: "Bank transfer",
    other: "Other",
    savePayment: "Save payment",
    savedSuccessfully: "Saved successfully",
    workUpdated: "Work updated",
    paymentSaved: "Payment saved",
    workTypeAdded: "Work type added",
    shareReceiptTitle: "Share receipt",
    customerStatementTitle: "CUSTOMER ACCOUNT STATEMENT",
    sharedWorkDetails: "Work details",
    sharedQuantity: "Quantity",
    remainingBalance: "Remaining balance",
    totalPendingBalance: "Total pending balance",
    noPendingBalance: "No balance due",
    sendWhatsApp: "Send on WhatsApp",
    sendSms: "Send by SMS",
    done: "Done",
    receiptTitle: "TRACTOR WORK RECEIPT",
    receiptFarmer: "Farmer",
    receiptDate: "Date",
    receiptWork: "Work",
    receiptRate: "Rate",
    receiptTotal: "Total amount",
    receiptReceived: "Amount received",
    receiptBalance: "Balance due",
    thankYou: "Thank you",
    loginTitle: "Tractor Records",
    loginIllustrationAlt: "A farmer with a tractor in green farm fields",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    forgotPasswordTitle: "Get a password reset link",
    forgotPasswordHelp: "Enter the email registered to your account.",
    sendResetLink: "Send reset link",
    sendingResetLink: "Sending link...",
    resetEmailConfirmation: "If an account exists for this email, a password reset link will be sent.",
    backToLogin: "Back to sign in",
    changePassword: "Change password",
    changePasswordHelp: "Set a new password for your Supabase account.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    passwordRequirements: "Use a password that meets the length and security requirements configured in Supabase.",
    passwordsDoNotMatch: "The two passwords do not match.",
    passwordRequired: "Enter a new password.",
    currentPasswordRequired: "Enter your current password to continue.",
    updatePassword: "Update password",
    updatingPassword: "Updating password...",
    passwordChanged: "Password changed successfully.",
    passwordUpdateFailed: "We could not change the password. Please try again.",
    passwordTooShort: "Password must be at least {count} characters.",
    passwordLengthRule: "Use a longer password.",
    passwordCharacterRule: "Include the required letters, numbers, or special characters.",
    passwordLeakedRule: "This password is not secure. Use a different password.",
    passwordWeak: "The password does not meet the configured security requirements.",
    passwordSame: "The new password must be different from the current password.",
    reauthCode: "6-digit code from your email",
    reauthCodeHelp: "Enter the code sent to your email for this security check.",
    reauthCodeSent: "A verification code was sent to your email.",
    reauthCodeInvalid: "The verification code is incorrect or has expired.",
    reauthCurrentRequired: "Verify your current password for security.",
    resetPasswordTitle: "Set a new password",
    resetPasswordHelp: "Enter a new password for your account.",
    recoveryLinkInvalid: "This password reset link is invalid. Request another link.",
    recoveryLinkExpiredOrUsed: "This password reset link has expired or has already been used. Request another link.",
    requestAnotherLink: "Request another reset link",
    continueToApp: "Continue to the app",
    showPassword: "Show password",
    hidePassword: "Hide password",
    yourName: "Your Name",
    enterYourName: "Your full name",
    enterPhoneNumber: "10-digit mobile number",
    signIn: "Sign in",
    signUp: "Sign Up",
    registerBtn: "Create Account",
    signingUp: "Creating account...",
    createAccount: "Create New Account",
    registerHelp: "Sign up with your details to manage your tractor records.",
    alreadyHaveAccount: "Already have an account? Sign In",
    dontHaveAccount: "Don't have an account? Sign Up",
    registerSuccessCheckEmail: "Registration successful! Please sign in or check your email.",
    loginWelcome: "Welcome back",
    loginHelp: "Sign in to continue to your tractor records.",
    loginSecurityNote: "Your account is secure",
    signingIn: "Signing in...",
    privateRecords: "Only you can see your records.",
    setupTitle: "Connect Supabase",
    setupOnce: "One-time setup",
    setupHelp: "Add the two Supabase values to .env.local, then restart the app.",
    setupDocs: "Full instructions are in README.md.",
    close: "Close",
    noWorkTypes: "No work types. Add one from the Work types page.",
    invalidAmounts: "Enter a quantity above zero and a non-negative rate.",
    totalBelowPaid: "Total cannot be less than payments already received ({amount}).",
    receivedTooHigh: "Amount received cannot be greater than the total amount.",
    chooseWorkType: "Select a work type.",
    enterFarmerName: "Enter the farmer name.",
    chooseFarmer: "Select a farmer.",
    choosePaymentMethod: "Select a payment method.",
    paymentPositive: "Enter a payment greater than zero.",
    paymentTooHigh: "Payment cannot be more than the balance ({amount}).",
    customerOutstandingBalance: "Total outstanding balance",
    remainingAfterPayment: "Remaining balance after this payment",
    oldestWorkAllocationHelp: "This payment is applied to the oldest pending work first.",
    customerPaymentSaved: "Customer payment saved successfully.",
    customerBalanceChanged: "The outstanding balance changed. Refresh the details and try again.",
    paymentRequestConflict: "This payment request was reused with different details. Close and reopen the form.",
    workSavedPaymentFailed: "Work saved, but payment failed: {error}",
    technicalError: "The action failed. Please try again. Details: {error}",
    sessionExpired: "Your session expired. Please sign in again.",
    invalidLogin: "The email or password is incorrect.",
    networkError: "Check your internet connection and try again.",
    appTagline: "Your tractor accounts, now on your mobile",
    greeting: "Namaskaram",
    pendingDuesSection: "Pending Balances",
    viewAll: "View all",
    addNewWorkHome: " Add New Work",
    addNewCustomer: "New Customer",
    customerDetails: "Customer Details",
    whoseWork: "Whose work?",
    whatWorkDone: "What work was done?",
    howManyAcres: "How many acres?",
    howManyHours: "How many hours?",
    ratePerAcreShort: "Rate per acre",
    ratePerHourShort: "Rate per hour",
    nowReceived: "Amount received now",
    saveWorkBtn: "Save Work",
    recordPaymentBtn: "Record Payment",
    currentBalance: "Current Balance",
    howMuchPaid: "Amount Paid",
    remainingBalanceDue: "Remaining Balance",
    workSavedTitle: "Work Saved!",
    shareOnWhatsApp: "Send on WhatsApp",
    goToHome: "Go to Home",
    oldRecords: "Work History",
    allWorks: "All",
    workTypesAndRates: "Work Types & Rates",
    addWorkType: "Add work type",
    editWorkType: "Edit work type",
    editCustomer: "Edit farmer",
    configuredRateMissing: "Set rate",
    customerUpdated: "Farmer details updated",
    payableBalanceLabel: "Balance to be paid",
    workTypeName: "Work type name",
    workTypeImage: "Work image",
    workTypeImageHelp: "Optional · JPEG, PNG, WebP · Maximum 2 MB. Choose only work illustrations without personal information.",
    changeWorkTypeImage: "Change image",
    removeWorkTypeImage: "Remove image",
    imageInvalidType: "Choose a JPEG, PNG or WebP image.",
    imageTooLarge: "The image must be 2 MB or smaller.",
    workTypeUnavailable: "Work type unavailable. Return to the work types page.",
    enterWorkTypeName: "Enter a work type name.",
    invalidRate: "Rates must be zero or greater.",
    workTypeUpdated: "Work type updated",
    rateNotConfigured: "Set or enter a rate.",
    unsavedChangesPrompt: "You have unsaved changes. What would you like to do?",
    continueEditing: "Continue editing",
    discardChanges: "Discard changes",
    changePasswordOption: "Change Password",
    call: "Call",
    navHome: "Home",
    navCustomers: "Farmers",
    navWork: "Work",
    navPending: "Dues",
    navSettings: "Settings",
    fullyPaid: "Fully Paid",
    pendingDueBadge: "Due",
    loginBtn: "Login",
    noPendingDues: "No pending dues currently",
  },
} as const;

export type MessageKey = keyof typeof messages.en;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: MessageKey, values?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("te");

  useEffect(() => {
    const timer = window.setTimeout(() => {
      const saved = window.localStorage.getItem("tractor-language");
      if (saved === "te" || saved === "en") {
        setLanguageState(saved);
        document.documentElement.lang = saved;
      }
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: (nextLanguage) => {
      setLanguageState(nextLanguage);
      window.localStorage.setItem("tractor-language", nextLanguage);
      document.documentElement.lang = nextLanguage;
    },
    t: (key, values) => {
      let result: string = messages[language][key];
      for (const [name, replacement] of Object.entries(values ?? {})) {
        result = result.replace(`{${name}}`, String(replacement));
      }
      return result;
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}

export function friendlyError(message: string, t: LanguageContextValue["t"]) {
  const lower = message.toLowerCase();
  if (lower.includes("invalid login") || lower.includes("invalid credentials")) return t("invalidLogin");
  if (lower.includes("jwt") || lower.includes("session")) return t("sessionExpired");
  if (lower.includes("fetch") || lower.includes("network")) return t("networkError");
  return t("technicalError", { error: message });
}
